### ISSUE TITLE
Exception occured when ran on OpenLiberty 

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/krazo#147]
Tried to deploy my [sample application](https://github.com/hantsy/jakartaee-mvc-sample) into the latest OpenLiberty 20.0.0.1 by maven plugin.

* OpenLiberty 20.0.0.1
* AdoptOpenJDK 8
* Win 10

```
mvn clean package liberty:create dependency:copy liberty:run -Popenliberty
```
When access http://localhost:9080/jakartaee-mvc-sample/mvc/tasks

Got exception info in the page.

```bash
 Exception thrown by application class 'java.util.Objects.requireNonNull:228'
java.lang.NullPointerException: Cannot produce UriInfo
at java.util.Objects.requireNonNull(Objects.java:228)
at org.eclipse.krazo.jaxrs.JaxRsContextProducer.produceUriInfo(JaxRsContextProducer.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
at [internal classes]
at org.jboss.weldx.ws.rs.core.UriInfo$311521641$Proxy$_$$_WeldClientProxy.getRequestUri(Unknown Source)
at com.example.MvcEventListener.lambda$onControllerMatched$0(MvcEventListener.java:21)
at java.util.logging.Logger.log(Logger.java:809)
at java.util.logging.Logger.info(Logger.java:1598)
at com.example.MvcEventListener.onControllerMatched(MvcEventListener.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
at [internal classes]
at org.eclipse.krazo.lifecycle.EventDispatcher.fireBeforeControllerEvent(EventDispatcher.java:55)
at org.eclipse.krazo.lifecycle.RequestLifecycle.aroundController(RequestLifecycle.java:61)
at org.eclipse.krazo.lifecycle.RequestLifecycle$Proxy$_$$_WeldClientProxy.aroundController(Unknown Source)
at org.eclipse.krazo.cdi.AroundControllerInterceptor.validateMethodInvocation(AroundControllerInterceptor.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
at [internal classes]
at org.eclipse.krazo.binding.validate.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
at [internal classes]
at com.example.web.TaskController$Proxy$_$$_WeldSubclass.allTasks(Unknown Source)
at com.example.web.TaskController$Proxy$_$$_WeldClientProxy.allTasks(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
at [internal classes]

```
And the mvn command line console threw the following info.

``` bash 
[INFO] [WARNING ] CWWKW1002W: The CDI scope of JAXRS-2.0 Provider PrimitiveConverterProvider is javax.enterprise.context.Dependent. Liberty gets the provider instance from CDI.
[INFO] [WARNING ] CWWKW1002W: The CDI scope of JAXRS-2.0 Provider PostNotFoundExceptionMapper is javax.enterprise.context.Dependent. Liberty gets the provider instance from CDI.
[INFO] [WARNING ] Application {http://web.example.com/}GreetingController has thrown exception, unwinding now
[INFO] Cannot produce UriInfo
[INFO] [WARNING ] Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@3aadd415
[INFO] Cannot produce UriInfo
[INFO] [ERROR   ] An unexpected error occurred during error handling. No further error processing will occur.
[INFO] Cannot produce UriInfo
[INFO] [ERROR   ] SRVE0777E: Exception thrown by application class 'java.util.Objects.requireNonNull:228'
[INFO] java.lang.NullPointerException: Cannot produce UriInfo
[INFO]  at java.util.Objects.requireNonNull(Objects.java:228)
[INFO]  at org.eclipse.krazo.jaxrs.JaxRsContextProducer.produceUriInfo(JaxRsContextProducer.java:82)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[INFO]  at [internal classes]
[INFO]  at org.jboss.weldx.ws.rs.core.UriInfo$311521641$Proxy$_$$_WeldClientProxy.getRequestUri(Unknown Source)
[INFO]  at com.example.MvcEventListener.lambda$onControllerMatched$0(MvcEventListener.java:21)
[INFO]  at java.util.logging.Logger.log(Logger.java:809)
[INFO]  at java.util.logging.Logger.info(Logger.java:1598)
[INFO]  at com.example.MvcEventListener.onControllerMatched(MvcEventListener.java:21)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[INFO]  at [internal classes]
[INFO]  at org.eclipse.krazo.lifecycle.EventDispatcher.fireBeforeControllerEvent(EventDispatcher.java:55)
[INFO]  at org.eclipse.krazo.lifecycle.RequestLifecycle.aroundController(RequestLifecycle.java:61)
[INFO]  at org.eclipse.krazo.lifecycle.RequestLifecycle$Proxy$_$$_WeldClientProxy.aroundController(Unknown Source)
[INFO]  at org.eclipse.krazo.cdi.AroundControllerInterceptor.validateMethodInvocation(AroundControllerInterceptor.java:48)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
[INFO]  at [internal classes]
[INFO]  at org.eclipse.krazo.binding.validate.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:96)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
[INFO]  at [internal classes]
[INFO]  at com.example.web.TaskController$Proxy$_$$_WeldSubclass.allTasks(Unknown Source)
[INFO]  at com.example.web.TaskController$Proxy$_$$_WeldClientProxy.allTasks(Unknown Source)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
[INFO]  at [internal classes]
[INFO]
[INFO] [ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.NullPointerException: Cannot produce UriInfo
[INFO]  at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5075)
[INFO]  at [internal classes]
[INFO] Caused by: java.lang.NullPointerException: Cannot produce UriInfo
[INFO]  at java.util.Objects.requireNonNull(Objects.java:228)
[INFO]  at org.eclipse.krazo.jaxrs.JaxRsContextProducer.produceUriInfo(JaxRsContextProducer.java:82)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[INFO]  at [internal classes]
[INFO]  at org.jboss.weldx.ws.rs.core.UriInfo$311521641$Proxy$_$$_WeldClientProxy.getRequestUri(Unknown Source)
[INFO]  at com.example.MvcEventListener.lambda$onControllerMatched$0(MvcEventListener.java:21)
[INFO]  at java.util.logging.Logger.log(Logger.java:809)
[INFO]  at java.util.logging.Logger.info(Logger.java:1598)
[INFO]  at com.example.MvcEventListener.onControllerMatched(MvcEventListener.java:21)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[INFO]  at [internal classes]
[INFO]  at org.eclipse.krazo.lifecycle.EventDispatcher.fireBeforeControllerEvent(EventDispatcher.java:55)
[INFO]  at org.eclipse.krazo.lifecycle.RequestLifecycle.aroundController(RequestLifecycle.java:61)
[INFO]  at org.eclipse.krazo.lifecycle.RequestLifecycle$Proxy$_$$_WeldClientProxy.aroundController(Unknown Source)
[INFO]  at org.eclipse.krazo.cdi.AroundControllerInterceptor.validateMethodInvocation(AroundControllerInterceptor.java:48)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
[INFO]  at [internal classes]
[INFO]  at org.eclipse.krazo.binding.validate.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:96)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
[INFO]  at [internal classes]
[INFO]  at com.example.web.TaskController$Proxy$_$$_WeldSubclass.allTasks(Unknown Source)
[INFO]  at com.example.web.TaskController$Proxy$_$$_WeldClientProxy.allTasks(Unknown Source)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
[INFO]  ... 1 more
[INFO]
```

**Comment by chkal** [comment]
Thanks for reporting this.

Does this only happen if you use the Maven plugin for deployment?

The error basically means that the container did not invoke `PostMatchingRequestFilter` and `PreMatchingRequestFilter` which are JAX-RS filters and automatically registered during the bootstrapping phase. Do you see the `"Initializing Eclipse Krazo...` in the logs?

**Comment by hantsy** [comment]
It indicated `UriInfo` is not produced as expected when ran it on OpenLiberty, so there is an exception in my Listener bean, the `UriInfo` is null.

**Comment by chkal** [comment]
> I have to add them to my MVC `Application` to declare them explicitly?

Actually all this should be performed automatically. However, you could try to manually register them:

https://github.com/eclipse-ee4j/krazo/blob/1bde7ff1ddec2511c5cdb0534803ee2495655191/core/src/main/java/org/eclipse/krazo/bootstrap/DefaultConfigProvider.java#L42-L54

**Comment by erdlet** [comment]
It seems that the observed `BeforeControllerEvent` isn't able to access the `UriInfo` applied to it:
```
   private void onControllerMatched(@Observes BeforeControllerEvent event) {
        LOGGER.info(() -> "Controller matched for " + event.getUriInfo().getRequestUri());
    }
```

@hantsy Is this working as expected when running on other containers like Glassfish or Wildfly? 
If yes, I'd assume that this is more a CXF issue.

**Comment by hantsy** [comment]
@erdlet Yes, It works on Payara and Wildfly, but did not work on OpenLiberty.

**Comment by hantsy** [comment]
When add the jaxrs feature classes expilictly, the home page is displayed, but when I click the *new task*(a form ), and submit and got a blank page. The exception is shown in console. 

```
[INFO] [WARNING ] SRVE8115W: WARNING: Cannot set status. Response already committed.
[INFO] [WARNING ] SRVE8094W: WARNING: Cannot set header. Response already committed.  Stack trace of errant attempt to set header:
[INFO]         at com.ibm.ws.webcontainer.srt.SRTServletResponse.setHeader(SRTServletResponse.java:1759)
[INFO]         at [internal classes].(Unknown Source)
[INFO]         at org.eclipse.krazo.core.ViewableWriter$DelegatingServletOutputStream.write(ViewableWriter.java:248)
[INFO]         at java.io.OutputStream.write(OutputStream.java:116)
[INFO]         at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
[INFO]         at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
[INFO]         at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
[INFO]         at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
[INFO]         at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
[INFO]         at java.io.PrintWriter.flush(PrintWriter.java:320)
[INFO]         at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:169)
[INFO]         at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:70)
[INFO]         at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1479)
[INFO]         at [internal classes].(Unknown Source)
[INFO]
```

**Comment by erdlet** [comment]
Thanks for that additional information. The new exceptions are known issues (see #132).

I hope I'll find some time this evening or tomorrow to have a further look on this issue.

**Comment by erdlet** [comment]
@hantsy: 
I tried your example as described on OpenJDK 8 and OpenJDK 11 and could not reproduce the initial problem with the `UriInfo`. Can you please checkout a clean version of your repo and try again? Maybe there was some pollution of your workspace.

The seconds problem regarding the form is more interesting, as it returns a HTTP 403 in the browser's network console. I'll have a look on this, as this may indicate a CSRF problem.

**Comment by erdlet** [comment]
>... but when I click the new task(a form ), and submit and got a blank page...

I checked this and recognized, that CXF doesn't return a session in the `SessionCsrfTokenStrategy` when Krazo wants to extract the token, which results in an exception which is unfortunately not logged by OpenLiberty. RestEasy and Jersey do this as expected. So this seems really to be an CXF issue we must address. I'll open another issue for tracking this, so we can focus on the `UriInfo` problem in this one.

**Comment by hantsy** [comment]
>I tried your example as described on OpenJDK 8 and OpenJDK 11 and could not reproduce the initial problem with the UriInfo. Can you please checkout a clean version of your repo and try again? Maybe there was some pollution of your workspace.

Maybe some codes changed,  in the original codes,  `getClasses()` of `Application`(`MvcConfig`) is overridden. 

```java
@Override
public Set<Class<?>> getClasses() {
        Set<Class<?>> classes = new HashSet<>();        
       classes.add(TaskController.class);
       classes.add(GreetingController.class);
       classes.add(LocaleController.class);
       classes.add(PrimitiveConverterProvider.class);
       classes.add(PostNotFoundExceptionMapper.class);
}
```

**Comment by erdlet** [comment]
Hello again,

I tried the example with the mentioned configuration and was able to reproduce the issue. It seems, that the `JaxRsContextProducer` isn't filled when using the `Application#getClasses` method on OpenLiberty. 

@chkal Do you have an idea what that probably could be?

**Comment by chkal** [comment]
> @chkal Do you have an idea what that probably could be?

IIRC this is a known JAX-RS issue. If you implement `getClasses()`, you basically disable auto-discovery of all JAX-RS component that are normally picked up automatically if you add `@Provider`. Unfortunately this also includes providers of "libraries" like Krazo and especially the [CoreFeature](https://github.com/eclipse-ee4j/krazo/blob/236b5bbed18a43beed1b71ce76ecc1c183608ef4/core/src/main/java/org/eclipse/krazo/bootstrap/CoreFeature.java) which triggers the Krazo initialization.

Jersey offers the `ForcedAutoDiscovery` API which [we are using](https://github.com/eclipse-ee4j/krazo/blob/236b5bbed18a43beed1b71ce76ecc1c183608ef4/jersey/src/main/java/org/eclipse/krazo/jersey/bootstrap/KrazoJerseyFeature.java#L40) to work around this problem. 

RESTEasy uses a `ServiceLoader` like approach we are [using here](https://github.com/eclipse-ee4j/krazo/blob/master/resteasy/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers) to force provider registration.

Not sure if there is something similar for CXF.

**Comment by erdlet** [comment]
OK, so it seems like we need some special initializer for Krazo like we have for the other implementations. I think we should open a new issue for that, so we can track what has to be done for CXF.

> Not sure if there is something similar for CXF.

CXF has something called `Feature`, which may be useful when I understood this integration point correct. But it isn't that handy like e.g. the Jersey or RESTEasy SPIs are.

**Comment by chkal** [comment]
> OK, so it seems like we need some special initializer for Krazo like we have for the other implementations. I think we should open a new issue for that, so we can track what has to be done for CXF.

:+1:

**Comment by erdlet** [comment]
As we have #157 for this issue, I'd close this now to have only one issue tracking the initialization problem.
