### ISSUE TITLE
Tests help using  Arqillian Dron and Arquillian Graphene

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/krazo#153]
In my [mvc sample](https://github.com/hantsy/jakartaee-mvc-sample), I have tried to [use Arqillian Dron and Arquillian Graphene to test the web pages](https://github.com/hantsy/jakartaee-mvc-sample/tree/f94a3b7f8f77303a21a61c43922faa12b46456f2), but it did not work when testing against Payara embedded/Managed.

In the latest version, I have tried to switch to use HtmlUnit instead, but it works on payara managed failed on payara embedded, check the [build log](https://github.com/hantsy/jakartaee-mvc-sample/runs/425119297).

I created another  [JakartaEE Server Faces sample](https://github.com/hantsy/jakartaee-faces-sample) used similar test codes, the tests are passed as expected. 

I have explored the krazo source codes, it seems the testing is based on HtmlUnit, is there are any samples that run the tests on the Jakarta EE compatible servers, e.g. Glassfish/Payara ?

**Comment by erdlet** [comment]
Hi @hantsy ,

sorry for the delay. 

> I have explored the krazo source codes, it seems the testing is based on HtmlUnit, is there are any samples that run the tests on the Jakarta EE compatible servers, e.g. Glassfish/Payara ?

Unfortunately, the only samples I can provide are the tests from our [testsuite](https://github.com/eclipse-ee4j/krazo/tree/master/testsuite). In the [pom.xml](https://github.com/eclipse-ee4j/krazo/blob/master/testsuite/pom.xml) you'll find profiles which run against Payara, Wildfly and TomEE. The run configurations of our CI pipeline which executes the testsuite can be found [here](https://github.com/eclipse-ee4j/krazo/blob/master/.travis.yml) and [here](https://github.com/eclipse-ee4j/krazo/tree/master/.travis). 

Hope that helps a little bit.

**Comment by hantsy** [comment]
In the testsuite, the [MvcIT](https://github.com/eclipse-ee4j/krazo/blob/master/testsuite/src/test/java/org/eclipse/krazo/test/MvcIT.java) is similar to my commit using HtmlUnit(use Arquillian to deploy it test runtime). But when I restore to Ariquillian Drone and Arquillian Graphene which provides more friendly APIs than HtmlUnit, it is still problematic.

Not sure if there are dependencies conflict or others. 

When I ran my tests  via command.

```bash
mvn clean verify -Parq-payara-embedded,jersey 
```

Got some exception like this:

```bash
Feb 12, 2020 3:29:26 PM org.eclipse.krazo.bootstrap.Initializer initialize
INFO: Initializing Eclipse Krazo...
Feb 12, 2020 3:29:27 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 8
org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=Instance<Models>,parent=ViewableWriter,qualifiers={},position=-1,optional=false,self=false,unqualified=null,825134767)
        at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:51)
        at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
        at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
        at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140)
        at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
        at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:308)
        at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:151)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:244)
        at org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:113)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$2(ApplicationHandler.java:349)
        at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:349)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:346)
        at javax.servlet.GenericServlet.init(GenericServlet.java:180)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1521)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1329)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5507)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5752)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:619)
        at org.apache.catalina.core.ContainerBase.startChildren(ContainerBase.java:1551)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1223)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:919)
        at org.apache.catalina.core.ContainerBase.startChildren(ContainerBase.java:1551)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1223)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:383)
        at org.apache.catalina.startup.Embedded.start(Embedded.java:929)
        at com.sun.enterprise.web.WebContainer.postConstruct(WebContainer.java:631)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
        at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
        at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.internal.data.EngineInfo.getContainer(EngineInfo.java:86)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.startContainers(ApplicationLifecycle.java:1122)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.startEngine(ApplicationLifecycle.java:964)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:796)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:424)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:538)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:584)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:576)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:575)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1496)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:137)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:113)
        at fish.payara.arquillian.container.payara.embedded.PayaraContainer.deploy(PayaraContainer.java:227)
        at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:151)
        at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:118)
        at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:239)
        at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
        at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createDeploymentContext(ContainerDeploymentContextHandler.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian
```

**Comment by chkal** [comment]
Looks like the stack trace refers to this injection point:

https://github.com/eclipse-ee4j/krazo/blob/236b5bbed18a43beed1b71ce76ecc1c183608ef4/core/src/main/java/org/eclipse/krazo/core/ViewableWriter.java#L76-L77

Not sure what the problem is here. This is a standard CDI injection point that uses CDI's `Instance`. Either the usage of `Instance` is a problem for some reason or CDI injection doesn't work at all. But in this case it would be weird that the error is thrown for this special `Instance` injection point.

The log also contains:

> stack 1 of 8

Are there more similar errors?

**Comment by chkal** [comment]
I just saw that there is one error for each injection point of `ViewableWriter`. So `Instance` doesn't seem to be the problem. I guess for some reason CDI injection isn't working it all. But I've no idea why.

**Comment by hantsy** [comment]
Today, I cleaned the codes and found the reason, when using *mvc/tasks* like URI to navigate the URL in `WebDriver`, it did not work. After I added a default page, *index.html* and add a like to *mvc/tasks*, it works.

* [index.html] (https://github.com/hantsy/jakartaee-mvc-sample/blob/master/src/main/webapp/index.html#L45)
* [Tests](https://github.com/hantsy/jakartaee-mvc-sample/blob/master/src/test/java/com/example/it/HomeScreenTest.java#L94-L98)

**Comment by chkal** [comment]
> Today, I cleaned the codes and found the reason, when using _mvc/tasks_ like URI to navigate the URL in `WebDriver`, it did not work. After I added a default page, _index.html_ and add a like to _mvc/tasks_, it works.

A URI like `mvc/tasks` is *relative*. In case of a link in an HTML page the URI is relative to the HTML page. So I guess that using an absolute URI by adding the application's context path fixes the issue.

**Comment by hantsy** [comment]
I see.
I think the problem is the `@Location` annotation to resolve the view path.
