### ISSUE TITLE
AvailableConvertersIT fails Glassfish build at Jenkins

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#276]
Since a while there are errors in the `AvailableConvertersIT` when running Krazo against Glasshfish 6.2.2 on JDK 11 and 17. We need to investigate this.

**Comment by erdlet** [comment]
This behavior is reproducable on my local setup. 

```
java.lang.ClassNotFoundException: javax.servlet.http.HttpServlet
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1577)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1427)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:1015)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1544)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1427)
        at org.apache.catalina.core.StandardWrapper.loadServletClass(StandardWrapper.java:1391)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1257)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:1069)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:136)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:119)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:611)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:550)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:75)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:114)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:199)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

I could imagine that this can be an Arquillian problem, because all other tests are running great and I had some similar problem at another project. This is one of the only tests injecting a bean directly into the test, whereas other tests are calling HTTP endpoints. Maybe, as a workaround, we could replace this test with something that uses direct HTTP calls instead of injecting the bean itself. Any other thoughts?

**Comment by chkal** [comment]
I wonder why it is complaining about `**javax**.servlet.http.HttpServlet`. Could really be caused by Arquillian. Didn't we update Arquillian some time ago?

**Comment by erdlet** [comment]
AFAIK we still use a release version of Arquillian which is based on the `javax` namespace. I‘ll investigate this if I can find some free time this week. Maybe we just need to use one of the current development versions of Arquillian.

**Comment by chkal** [comment]
Awesome! Thanks.

BTW: I guess you are correct. This is a test which doesn't run outside, but inside the container, which is a pretty rare case for us. So it may really be caused by Arquillian vs. Jakarta EE 9.

**Comment by erdlet** [comment]
I tried to update Arquillian but it had no effect on this test. Really weird. Anyway, as this is the AFAIK the only test running inside the container, I'll write a version that runs outside of it and uses a simple web page.
