### ISSUE TITLE
Fix failing TCK test on WildFly for Krazo 3.0.0

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#342]
Krazo 3.0.0 fails on WildFly 27 because of this:

```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.861 s <<< FAILURE! - in jakarta.mvc.tck.tests.binding.base.BindingBaseTest
[ERROR] submitValidationError(jakarta.mvc.tck.tests.binding.base.BindingBaseTest)  Time elapsed: 0.349 s  <<< ERROR!
java.lang.ClassCastException: class com.gargoylesoftware.htmlunit.xml.XmlPage cannot be cast to class com.gargoylesoftware.htmlunit.html.HtmlPage (com.gargoylesoftware.htmlunit.xml.XmlPage and com.gargoylesoftware.htmlunit.html.HtmlPage are in unnamed module of loader 'app')
	at jakarta.mvc.tck.tests.binding.base.BindingBaseTest.submitForm(BindingBaseTest.java:122)
	at jakarta.mvc.tck.tests.binding.base.BindingBaseTest.submitValidationError(BindingBaseTest.java:90)
```

We need to investigate and fix the issue. The only change happened in the RESTEasy package within the last months was fixing the handling of mixed Jakarta REST Resources in [this commit](https://github.com/eclipse-ee4j/krazo/commit/ce2fa05f0290dc920c26457ee9144d134256bade)

**Comment by erdlet** [comment]
This needs to be backported to a bugfix release of Krazo 3.0.x.
